env:
  SAUCECTL_LABEL: "$BUILDKITE_BUILD_NUMBER $BUILDKITE_PIPELINE_SLUG $BUILDKITE_BRANCH $BUILDKITE_COMMIT"
steps:
- agents: [dind=true,queue=beta]
  command: ./.buildkite/publish.sh
  label: Build AARs and APKs
  plugins:
    - artifacts#v1.3.0:
        upload:
          - "MuxExoPlayer/buildout/outputs/artifacts/*.aar"
          - "MuxExoPlayer/buildout/outputs/artifacts/*.txt"
          - "MuxExoPlayer/buildout/outputs/version-*"
          - "MuxExoPlayer/buildout/reports/*/*.*"
          - "automatedtests/buildout/outputs/apk/androidTest/**/*.apk"
          - "automatedtests/buildout/outputs/apk/*/debug/automatedtests-*-debug.apk"
#- wait
#- agents: [dind=true,queue=beta]
#  command: docker run --rm -v $(pwd):/data -e BUILD_LABEL="$SAUCECTL_LABEL" -e TEST_APK=/data/automatedtests/buildout/outputs/apk/androidTest/r2_9_6/debug/automatedtests-r2_9_6-debug-androidTest.apk -e APP_APK=/data/automatedtests/buildout/outputs/apk/r2_9_6/debug/automatedtests-r2_9_6-debug.apk -e TEST_DEVICES='Google Pixel[ 345]*' -e SAUCE_USERNAME='mux-sauce' -e SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY muxinc/saucectl-runner:0.54.0-22f296b
#  label: Test Exoplayer r2_9_6 on Pixel device
#  retry:
#    automatic:
#      - exit_status: 1
#        limit: 2
#  plugins:
#    - artifacts#v1.3.0:
#        download:
#          - "automatedtests/buildout/outputs/apk/r2_9_6/debug/automatedtests-r2_9_6-debug.apk"
#          - "automatedtests/buildout/outputs/apk/androidTest/r2_9_6/debug/automatedtests-r2_9_6-debug-androidTest.apk"
#- wait
#- agents: [dind=true,queue=beta]
#  command: docker run --rm -v $(pwd):/data -e BUILD_LABEL="$SAUCECTL_LABEL" -e TEST_APK=/data/automatedtests/buildout/outputs/apk/androidTest/r2_10_6/debug/automatedtests-r2_10_6-debug-androidTest.apk -e APP_APK=/data/automatedtests/buildout/outputs/apk/r2_10_6/debug/automatedtests-r2_10_6-debug.apk -e TEST_DEVICES='Google Pixel[ 345]*' -e SAUCE_USERNAME='mux-sauce' -e SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY muxinc/saucectl-runner:0.54.0-22f296b
#  label: Test Exoplayer r2_10_6 on Pixel device
#  retry:
#    automatic:
#      - exit_status: 1
#        limit: 2
#  plugins:
#    - artifacts#v1.3.0:
#        download:
#          - "automatedtests/buildout/outputs/apk/r2_10_6/debug/automatedtests-r2_10_6-debug.apk"
#          - "automatedtests/buildout/outputs/apk/androidTest/r2_10_6/debug/automatedtests-r2_10_6-debug-androidTest.apk"
#- wait
#- agents: [dind=true,queue=beta]
#  command: docker run --rm -v $(pwd):/data -e BUILD_LABEL="$SAUCECTL_LABEL" -e TEST_APK=/data/automatedtests/buildout/outputs/apk/androidTest/r2_11_1/debug/automatedtests-r2_11_1-debug-androidTest.apk -e APP_APK=/data/automatedtests/buildout/outputs/apk/r2_11_1/debug/automatedtests-r2_11_1-debug.apk -e TEST_DEVICES='Google Pixel[ 345]*' -e SAUCE_USERNAME='mux-sauce' -e SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY muxinc/saucectl-runner:0.54.0-22f296b
#  label: Test Exoplayer r2_11_1 on Pixel device
#  retry:
#    automatic:
#      - exit_status: 1
#        limit: 2
#  plugins:
#    - artifacts#v1.3.0:
#        download:
#          - "automatedtests/buildout/outputs/apk/r2_11_1/debug/automatedtests-r2_11_1-debug.apk"
#          - "automatedtests/buildout/outputs/apk/androidTest/r2_11_1/debug/automatedtests-r2_11_1-debug-androidTest.apk"
#- wait
#- agents: [dind=true,queue=beta]
#  command: docker run --rm -v $(pwd):/data -e BUILD_LABEL="$SAUCECTL_LABEL" -e TEST_APK=/data/automatedtests/buildout/outputs/apk/androidTest/r2_12_1/debug/automatedtests-r2_12_1-debug-androidTest.apk -e APP_APK=/data/automatedtests/buildout/outputs/apk/r2_12_1/debug/automatedtests-r2_12_1-debug.apk -e TEST_DEVICES='Google Pixel[ 345]*' -e SAUCE_USERNAME='mux-sauce' -e SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY muxinc/saucectl-runner:0.54.0-22f296b
#  label: Test Exoplayer r2_12_1 on Pixel device
#  retry:
#    automatic:
#      - exit_status: 1
#        limit: 2
#  plugins:
#    - artifacts#v1.3.0:
#        download:
#          - "automatedtests/buildout/outputs/apk/r2_12_1/debug/automatedtests-r2_12_1-debug.apk"
#          - "automatedtests/buildout/outputs/apk/androidTest/r2_12_1/debug/automatedtests-r2_12_1-debug-androidTest.apk"
#- wait
#- agents: [dind=true,queue=beta]
#  command: docker run --rm -v $(pwd):/data -e BUILD_LABEL="$SAUCECTL_LABEL" -e TEST_APK=/data/automatedtests/buildout/outputs/apk/androidTest/r2_13_1/debug/automatedtests-r2_13_1-debug-androidTest.apk -e APP_APK=/data/automatedtests/buildout/outputs/apk/r2_13_1/debug/automatedtests-r2_13_1-debug.apk -e TEST_DEVICES='Google Pixel[ 345]*' -e SAUCE_USERNAME='mux-sauce' -e SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY muxinc/saucectl-runner:0.54.0-22f296b
#  label: Test Exoplayer r2_13_1 on Pixel device
#  retry:
#    automatic:
#      - exit_status: 1
#        limit: 2
#  plugins:
#    - artifacts#v1.3.0:
#        download:
#          - "automatedtests/buildout/outputs/apk/r2_13_1/debug/automatedtests-r2_13_1-debug.apk"
#          - "automatedtests/buildout/outputs/apk/androidTest/r2_13_1/debug/automatedtests-r2_13_1-debug-androidTest.apk"
#- wait
#- agents: [dind=true,queue=beta]
#  command: docker run --rm -v $(pwd):/data -e BUILD_LABEL="$SAUCECTL_LABEL" -e TEST_APK=/data/automatedtests/buildout/outputs/apk/androidTest/r2_14_1/debug/automatedtests-r2_14_1-debug-androidTest.apk -e APP_APK=/data/automatedtests/buildout/outputs/apk/r2_14_1/debug/automatedtests-r2_14_1-debug.apk -e TEST_DEVICES='Google Pixel[ 345]*' -e SAUCE_USERNAME='mux-sauce' -e SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY muxinc/saucectl-runner:0.54.0-22f296b
#  label: Test Exoplayer r2_14_1 on Pixel device
#  retry:
#    automatic:
#      - exit_status: 1
#        limit: 2
#  plugins:
#    - artifacts#v1.3.0:
#        download:
#          - "automatedtests/buildout/outputs/apk/r2_14_1/debug/automatedtests-r2_14_1-debug.apk"
#          - "automatedtests/buildout/outputs/apk/androidTest/r2_14_1/debug/automatedtests-r2_14_1-debug-androidTest.apk"
#- wait
#- block: ":rocket: Deploy and release!"
#  blocked_state: failed
#  branches: "master"
#- wait
#- agents: [ dind=true,queue=beta ]
#  command: ./.buildkite/deploy.sh
#  label: Deploy artifacts to release maven if it all worked
#  branches: "master"
