env:
  BUILDKITE_PLUGIN_ARTIFACTS_DEBUG: 1
  BUILDKITE_PLUGIN_ARTIFACTS_BUILD: "${BUILDKITE_BUILD_ID}"
  SAUCECTL_LABEL: "$BUILDKITE_BUILD_NUMBER $BUILDKITE_PIPELINE_SLUG $BUILDKITE_BRANCH $BUILDKITE_COMMIT"
steps:
- agents: [dind=true,queue=beta]
  command: echo "Hello I am from $BUILDKITE_BUILD_NUMBER" > fixedname.txt; echo "I am unique made by $BUILDKITE_BUILD_NUMBER" > ${BUILDKITE_BUILD_NUMBER}_output.txt; ls -al; sleep 2m
  label: Final test
  plugins:
    - artifacts#v1.3.0:
        upload:
          - "fixedname.txt"
          - "*_output.txt"
- wait
- agents: [dind=true,queue=beta]
  command: echo This is $BUILDKITE_BUILD_NUMBER; ls -al; cat fixedname.txt; cat ${BUILDKITE_BUILD_NUMBER}_output.txt; sleep 2m
  label: Testing artifacts
  retry:
    automatic:
      - exit_status: 1
        limit: 2
  plugins:
    - artifacts#v1.3.0:
        download:
          - "fixedname.txt"
          - "*_output.txt"
- wait
- agents: [ dind=true,queue=beta ]
  command: echo This is $BUILDKITE_BUILD_NUMBER; ls -al; cat fixedname.txt; cat ${BUILDKITE_BUILD_NUMBER}_output.txt; sleep 2m
  label: Testing artifacts
  retry:
    automatic:
      - exit_status: 1
        limit: 2
  plugins:
    - artifacts#v1.3.0:
        download:
          - "fixedname.txt"
          - "*_output.txt"
- wait
- agents: [ dind=true,queue=beta ]
  command: echo This is $BUILDKITE_BUILD_NUMBER; ls -al; cat fixedname.txt; cat ${BUILDKITE_BUILD_NUMBER}_output.txt; sleep 2m
  label: Testing artifacts
  retry:
    automatic:
      - exit_status: 1
        limit: 2
  plugins:
    - artifacts#v1.3.0:
        download:
          - "fixedname.txt"
          - "*_output.txt"
- wait
- agents: [dind=true,queue=beta]
  command: echo This is $BUILDKITE_BUILD_NUMBER; ls -al; cat fixedname.txt; cat ${BUILDKITE_BUILD_NUMBER}_output.txt; sleep 2m
  label: Testing artifacts
  retry:
    automatic:
      - exit_status: 1
        limit: 2
  plugins:
    - artifacts#v1.3.0:
        download:
          - "fixedname.txt"
          - "*_output.txt"
- wait
- agents: [ dind=true,queue=beta ]
  command: echo This is $BUILDKITE_BUILD_NUMBER; ls -al; cat fixedname.txt; cat ${BUILDKITE_BUILD_NUMBER}_output.txt; sleep 2m
  label: Testing artifacts
  retry:
    automatic:
      - exit_status: 1
        limit: 2
  plugins:
    - artifacts#v1.3.0:
        download:
          - "fixedname.txt"
          - "*_output.txt"