env:
  SAUCECTL_LABEL: "$BUILDKITE_BUILD_NUMBER $BUILDKITE_PIPELINE_SLUG $BUILDKITE_BRANCH $BUILDKITE_COMMIT"
  BUILD_CI_ID: "$BUILDKITE_BUILD_NUMBER : $BUILDKITE_BRANCH : $BUILDKITE_COMMIT"
steps:
- agents: [dind=true,queue=beta]
  command: docker run -it --rm -v $(pwd):/data -e BUILD_CI_ID="$BUILD_CI_ID" -w="/data" muxinc/mux-exoplayer:20201215 bash -c "./gradlew --info MuxExoPlayer:clean MuxExoPlayer:build assemble automatedtests:assembleAndroidTest"
  label: Build AARs and APKs
  plugins:
    - artifacts#v1.3.0:
        upload:
          - "MuxExoPlayer/buildout/outputs/artifacts/*.aar"
          - "MuxExoPlayer/buildout/outputs/artifacts/*.txt"
          - "MuxExoPlayer/buildout/outputs/version-*"
          - "automatedtests/buildout/outputs/apk/androidTest/**/*.apk"
          - "automatedtests/buildout/outputs/apk/*/debug/automatedtests-*-debug.apk"
- wait
- agents: [dind=true,queue=beta]
  command: docker run --rm -v $(pwd):/data -e BUILD_LABEL="$SAUCECTL_LABEL" -e TEST_APK=/data/automatedtests/buildout/outputs/apk/androidTest/r2_9_6/debug/automatedtests-r2_9_6-debug-androidTest.apk -e APP_APK=/data/automatedtests/buildout/outputs/apk/r2_9_6/debug/automatedtests-r2_9_6-debug.apk -e TEST_DEVICES='Google Pixel 4' -e SAUCE_USERNAME='mux-sauce' -e SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY muxinc/saucectl-runner:0.55.0
  label: Test Exoplayer r2_9_6 on Pixel device
  retry:
    automatic:
      - exit_status: 1
        limit: 2
  plugins:
    - artifacts#v1.3.0:
        upload:
          - "artifacts/*/*.*"
        download:
          - "automatedtests/buildout/outputs/apk/r2_9_6/debug/automatedtests-r2_9_6-debug.apk"
          - "automatedtests/buildout/outputs/apk/androidTest/r2_9_6/debug/automatedtests-r2_9_6-debug-androidTest.apk"
- wait
- agents: [dind=true,queue=beta]
  command: docker run --rm -v $(pwd):/data -e BUILD_LABEL="$SAUCECTL_LABEL" -e TEST_APK=/data/automatedtests/buildout/outputs/apk/androidTest/r2_10_6/debug/automatedtests-r2_10_6-debug-androidTest.apk -e APP_APK=/data/automatedtests/buildout/outputs/apk/r2_10_6/debug/automatedtests-r2_10_6-debug.apk -e TEST_DEVICES='Google Pixel 4' -e SAUCE_USERNAME='mux-sauce' -e SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY muxinc/saucectl-runner:0.55.0
  label: Test Exoplayer r2_10_6 on Pixel device
  retry:
    automatic:
      - exit_status: 1
        limit: 2
  plugins:
    - artifacts#v1.3.0:
        upload:
          - "artifacts/*/*.*"
        download:
          - "automatedtests/buildout/outputs/apk/r2_10_6/debug/automatedtests-r2_10_6-debug.apk"
          - "automatedtests/buildout/outputs/apk/androidTest/r2_10_6/debug/automatedtests-r2_10_6-debug-androidTest.apk"
- wait
- agents: [dind=true,queue=beta]
  command: docker run --rm -v $(pwd):/data -e BUILD_LABEL="$SAUCECTL_LABEL" -e TEST_APK=/data/automatedtests/buildout/outputs/apk/androidTest/r2_11_1/debug/automatedtests-r2_11_1-debug-androidTest.apk -e APP_APK=/data/automatedtests/buildout/outputs/apk/r2_11_1/debug/automatedtests-r2_11_1-debug.apk -e TEST_DEVICES='Google Pixel 4' -e SAUCE_USERNAME='mux-sauce' -e SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY muxinc/saucectl-runner:0.55.0
  label: Test Exoplayer r2_11_1 on Pixel device
  retry:
    automatic:
      - exit_status: 1
        limit: 2
  plugins:
    - artifacts#v1.3.0:
        upload:
          - "artifacts/*/*.*"
        download:
          - "automatedtests/buildout/outputs/apk/r2_11_1/debug/automatedtests-r2_11_1-debug.apk"
          - "automatedtests/buildout/outputs/apk/androidTest/r2_11_1/debug/automatedtests-r2_11_1-debug-androidTest.apk"
- wait
- agents: [dind=true,queue=beta]
  command: docker run  --rm -v $(pwd):/data -e BUILD_LABEL="$SAUCECTL_LABEL" -e TEST_APK=/data/automatedtests/buildout/outputs/apk/androidTest/r2_12_1/debug/automatedtests-r2_12_1-debug-androidTest.apk -e APP_APK=/data/automatedtests/buildout/outputs/apk/r2_12_1/debug/automatedtests-r2_12_1-debug.apk -e TEST_DEVICES='Google Pixel 4' -e SAUCE_USERNAME='mux-sauce' -e SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY muxinc/saucectl-runner:0.55.0
  label: Test Exoplayer r2_12_1 on Pixel device
  retry:
    automatic:
      - exit_status: 1
        limit: 2
  plugins:
    - artifacts#v1.3.0:
        upload:
          - "artifacts/*/*.*"
        download:
          - "automatedtests/buildout/outputs/apk/r2_12_1/debug/automatedtests-r2_12_1-debug.apk"
          - "automatedtests/buildout/outputs/apk/androidTest/r2_12_1/debug/automatedtests-r2_12_1-debug-androidTest.apk"
- wait
- agents: [dind=true,queue=beta]
  command: docker run --rm -v $(pwd):/data -e BUILD_LABEL="$SAUCECTL_LABEL" -e TEST_APK=/data/automatedtests/buildout/outputs/apk/androidTest/r2_13_1/debug/automatedtests-r2_13_1-debug-androidTest.apk -e APP_APK=/data/automatedtests/buildout/outputs/apk/r2_13_1/debug/automatedtests-r2_13_1-debug.apk -e TEST_DEVICES='Google Pixel 4' -e SAUCE_USERNAME='mux-sauce' -e SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY muxinc/saucectl-runner:0.55.0
  label: Test Exoplayer r2_13_1 on Pixel device
  retry:
    automatic:
      - exit_status: 1
        limit: 2
  plugins:
    - artifacts#v1.3.0:
        upload:
          - "artifacts/*/*.*"
        download:
          - "automatedtests/buildout/outputs/apk/r2_13_1/debug/automatedtests-r2_13_1-debug.apk"
          - "automatedtests/buildout/outputs/apk/androidTest/r2_13_1/debug/automatedtests-r2_13_1-debug-androidTest.apk"
