steps:
- agents: [dind=true,queue=beta]
  command: docker run -it --rm -v $(pwd):/data -w="/data" muxinc/mux-exoplayer:20201215 bash -c "./gradlew --info MuxExoPlayer:clean MuxExoPlayer:build assemble automatedtests:assembleAndroidTest"
  label: Build AARs and APKs
  plugins:
    - artifacts#v1.3.0:
        upload:
          - "MuxExoPlayer/buildout/outputs/artifacts/*.aar"
          - "MuxExoPlayer/buildout/outputs/artifacts/*.txt"
          - "MuxExoPlayer/buildout/outputs/version-*"
          - "automatedtests/buildout/outputs/apk/androidTest/**/*.apk"
          - "automatedtests/buildout/outputs/apk/*/debug/automatedtests-*-debug.apk"
- wait
- agents: [ dind=true,queue=beta ]
  command: docker run --rm -v $(pwd):/data -e TEST_APK=/data/automatedtests/buildout/outputs/apk/androidTest/r2_9_6/debug/automatedtests-r2_9_6-debug-androidTest.apk -e APP_APK=/data/automatedtests/buildout/outputs/apk/r2_9_6/debug/automatedtests-r2_9_6-debug.apk -e SAUCE_USERNAME=$SAUCE_USERNAME -e SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY muxinc/saucectrl-runner
  label: Test Exoplayer r2_9_6 on Pixel device
  retry:
    automatic:
      - exit_status: 1
        limit: 2
  plugins:
    - artifacts#v1.3.0:
        download:
          - "automatedtests/buildout/outputs/apk/r2_9_6/debug/automatedtests-r2_9_6-debug.apk"
          - "automatedtests/buildout/outputs/apk/androidTest/r2_9_6/debug/automatedtests-r2_9_6-debug-androidTest.apk"