name: Deploy and Create Release

on:
  pull_request:
    types: [closed]

jobs:
  draft:
    if: startsWith(github.head_ref, 'releases/v') && github.event.pull_request.merged
    runs-on: ubuntu-latest
    name: Deploy and Release
    steps:
     - uses: actions/checkout@v2
     - name: Generate Version for ${{ github.head_ref }}
       id: version
       uses: AsasInnab/regex-action@v1
       with:
         regex_pattern: v\d+\.\d+\.\d+
         regex_flags: "gim"
         search_string: ${{ github.head_ref }}
     - name: Deploy to Release Maven
       uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
       with:
         arguments: muxReleaseDeploy
     - name: Create the release
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         tag_name: ${{ steps.version.outputs.first_match }}
         release_name: ${{ steps.version.outputs.first_match }}
         body: ${{ github.event.pull_request.body }}
         commitish: ${{ github.event.pull_request.head.sha }}
